trigger:
- main 
pool:
  vmImage: default

variables:
  builConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(builConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'